//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PokerHand {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PokerHand.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid card.
        /// </summary>
        internal static string Exception_InvalidCard {
            get {
                return ResourceManager.GetString("Exception_InvalidCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid card suit.
        /// </summary>
        internal static string Exception_InvalidCard_Suit {
            get {
                return ResourceManager.GetString("Exception_InvalidCard_Suit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid card value.
        /// </summary>
        internal static string Exception_InvalidCard_Value {
            get {
                return ResourceManager.GetString("Exception_InvalidCard_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A poker hand must have exactly 5 cards in it.
        /// </summary>
        internal static string Exception_InvalidHand_IncorrectNumberOfCards {
            get {
                return ResourceManager.GetString("Exception_InvalidHand_IncorrectNumberOfCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to example: 2C 3S 4C AD QH (enter 10 as T).
        /// </summary>
        internal static string HandFormat {
            get {
                return ResourceManager.GetString("HandFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter {0}&apos;s five-card hand: .
        /// </summary>
        internal static string HandPrompt {
            get {
                return ResourceManager.GetString("HandPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter player {0}&apos;s name: .
        /// </summary>
        internal static string NamePrompt {
            get {
                return ResourceManager.GetString("NamePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The poker hands are tied!.
        /// </summary>
        internal static string Result_Tie {
            get {
                return ResourceManager.GetString("Result_Tie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}&apos;s hand is the winner!.
        /// </summary>
        internal static string Result_Winner {
            get {
                return ResourceManager.GetString("Result_Winner", resourceCulture);
            }
        }
    }
}
